from typing import Protocol

from src.domain.entities.batch import Batch
from src.domain.shared.types import Reference


class BatchRepository(Protocol):
    def add(self, batch: Batch) -> None: ...
    def update(self, batch: Batch) -> None: ...
    def get(self, reference: Reference) -> Batch: ...
    def remove(self, reference: Reference) -> None: ...
