from typing import Protocol

from src.domain.shared.types import OrderReference
from src.domain.value_object.order_line import OrderLine


class OrderLineRepository(Protocol):
    def add(self, order_line: OrderLine) -> None: ...
    def update(self, order_line: OrderLine) -> None: ...
    def get(self, orderid: OrderReference) -> OrderLine: ...
    def remove(self, orderid: OrderReference) -> None: ...
